---
# Project
project_name: habit-tracker
deploy_dir: /opt/habit-tracker

# Domain (replace with real domain)
domain: example.com

# Docker Registry (GitHub Container Registry)
registry_url: ghcr.io
app_image: "ghcr.io/artsiomkuliashou/diplom/habit-tracker:latest"

# Database
db_name: habitdb
db_user: habituser
db_password: "{{ lookup('env', 'DB_PASSWORD') | default('change_me', true) }}"

# Monitoring
prometheus_port: 9090
grafana_port: 3000
node_exporter_port: 9100
cadvisor_port: 8081
postgres_exporter_port: 9187
blackbox_exporter_port: 9115

# Logging
elasticsearch_port: 9200
logstash_port: 5044
kibana_port: 5601

# App server IP (private IP for Prometheus scraping within VPC)
app_server_ip: "10.0.1.74"
monitoring_server_ip: "{{ hostvars['monitoring']['ansible_host'] }}"
