[app_servers]
app ansible_host=3.65.247.78
app2 ansible_host=63.183.175.232

[app_primary]
app ansible_host=3.65.247.78

[app_replica]
app2 ansible_host=63.183.175.232

[monitoring_servers]
monitoring ansible_host=3.124.150.179

[all:vars]
ansible_python_interpreter=/usr/bin/python3
