---
- name: Deploy application to primary app server
  hosts: app_primary
  become: yes
  roles:
    - app

- name: Deploy application to replica app server
  hosts: app_replica
  become: yes
  roles:
    - app
